// Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// --------------------------------------------------------------------------------
// Tool Version: Vivado v.2021.2 (lin64) Build 3367213 Tue Oct 19 02:47:39 MDT 2021
// Date        : Wed May 25 14:31:44 2022
// Host        : janux-03 running 64-bit Ubuntu 16.04.6 LTS
// Command     : write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
//               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ ulp_axi_vip_0_0_sim_netlist.v
// Design      : ulp_axi_vip_0_0
// Purpose     : This verilog netlist is a functional simulation representation of the design and should not be modified
//               or synthesized. This netlist cannot be used for SDF annotated simulation.
// Device      : xcku15p-ffva1156-2LV-e
// --------------------------------------------------------------------------------
`timescale 1 ps / 1 ps

(* CHECK_LICENSE_TYPE = "ulp_axi_vip_0_0,axi_vip_v1_1_11_top,{}" *) (* DowngradeIPIdentifiedWarnings = "yes" *) (* X_CORE_INFO = "axi_vip_v1_1_11_top,Vivado 2021.2" *) 
(* NotValidForBitStream *)
module decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix
   (aclk,
    aresetn,
    m_axi_awaddr,
    m_axi_awlen,
    m_axi_awsize,
    m_axi_awburst,
    m_axi_awlock,
    m_axi_awcache,
    m_axi_awprot,
    m_axi_awregion,
    m_axi_awqos,
    m_axi_awvalid,
    m_axi_awready,
    m_axi_wdata,
    m_axi_wstrb,
    m_axi_wlast,
    m_axi_wvalid,
    m_axi_wready,
    m_axi_bresp,
    m_axi_bvalid,
    m_axi_bready,
    m_axi_araddr,
    m_axi_arlen,
    m_axi_arsize,
    m_axi_arburst,
    m_axi_arlock,
    m_axi_arcache,
    m_axi_arprot,
    m_axi_arregion,
    m_axi_arqos,
    m_axi_arvalid,
    m_axi_arready,
    m_axi_rdata,
    m_axi_rresp,
    m_axi_rlast,
    m_axi_rvalid,
    m_axi_rready);
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 CLOCK CLK" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME CLOCK, ASSOCIATED_BUSIF S_AXI:M_AXI, ASSOCIATED_RESET ARESETN, FREQ_HZ 300000000, FREQ_TOLERANCE_HZ 0, PHASE 0, CLK_DOMAIN cd_kernel_ref_clk_00, INSERT_VIP 0" *) input aclk;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 RESET RST" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME RESET, POLARITY ACTIVE_LOW, INSERT_VIP 0, TYPE INTERCONNECT" *) input aresetn;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI AWADDR" *) output [38:0]m_axi_awaddr;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI AWLEN" *) output [7:0]m_axi_awlen;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI AWSIZE" *) output [2:0]m_axi_awsize;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI AWBURST" *) output [1:0]m_axi_awburst;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI AWLOCK" *) output [0:0]m_axi_awlock;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI AWCACHE" *) output [3:0]m_axi_awcache;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI AWPROT" *) output [2:0]m_axi_awprot;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI AWREGION" *) output [3:0]m_axi_awregion;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI AWQOS" *) output [3:0]m_axi_awqos;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI AWVALID" *) output m_axi_awvalid;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI AWREADY" *) input m_axi_awready;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI WDATA" *) output [511:0]m_axi_wdata;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI WSTRB" *) output [63:0]m_axi_wstrb;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI WLAST" *) output m_axi_wlast;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI WVALID" *) output m_axi_wvalid;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI WREADY" *) input m_axi_wready;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI BRESP" *) input [1:0]m_axi_bresp;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI BVALID" *) input m_axi_bvalid;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI BREADY" *) output m_axi_bready;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI ARADDR" *) output [38:0]m_axi_araddr;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI ARLEN" *) output [7:0]m_axi_arlen;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI ARSIZE" *) output [2:0]m_axi_arsize;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI ARBURST" *) output [1:0]m_axi_arburst;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI ARLOCK" *) output [0:0]m_axi_arlock;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI ARCACHE" *) output [3:0]m_axi_arcache;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI ARPROT" *) output [2:0]m_axi_arprot;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI ARREGION" *) output [3:0]m_axi_arregion;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI ARQOS" *) output [3:0]m_axi_arqos;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI ARVALID" *) output m_axi_arvalid;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI ARREADY" *) input m_axi_arready;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI RDATA" *) input [511:0]m_axi_rdata;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI RRESP" *) input [1:0]m_axi_rresp;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI RLAST" *) input m_axi_rlast;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI RVALID" *) input m_axi_rvalid;
  (* X_INTERFACE_INFO = "xilinx.com:interface:aximm:1.0 M_AXI RREADY" *) (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME M_AXI, DATA_WIDTH 512, PROTOCOL AXI4, FREQ_HZ 300000000, ID_WIDTH 0, ADDR_WIDTH 39, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0, CLK_DOMAIN cd_kernel_ref_clk_00, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0" *) output m_axi_rready;

  wire \<const0> ;

  assign m_axi_araddr[38] = \<const0> ;
  assign m_axi_araddr[37] = \<const0> ;
  assign m_axi_araddr[36] = \<const0> ;
  assign m_axi_araddr[35] = \<const0> ;
  assign m_axi_araddr[34] = \<const0> ;
  assign m_axi_araddr[33] = \<const0> ;
  assign m_axi_araddr[32] = \<const0> ;
  assign m_axi_araddr[31] = \<const0> ;
  assign m_axi_araddr[30] = \<const0> ;
  assign m_axi_araddr[29] = \<const0> ;
  assign m_axi_araddr[28] = \<const0> ;
  assign m_axi_araddr[27] = \<const0> ;
  assign m_axi_araddr[26] = \<const0> ;
  assign m_axi_araddr[25] = \<const0> ;
  assign m_axi_araddr[24] = \<const0> ;
  assign m_axi_araddr[23] = \<const0> ;
  assign m_axi_araddr[22] = \<const0> ;
  assign m_axi_araddr[21] = \<const0> ;
  assign m_axi_araddr[20] = \<const0> ;
  assign m_axi_araddr[19] = \<const0> ;
  assign m_axi_araddr[18] = \<const0> ;
  assign m_axi_araddr[17] = \<const0> ;
  assign m_axi_araddr[16] = \<const0> ;
  assign m_axi_araddr[15] = \<const0> ;
  assign m_axi_araddr[14] = \<const0> ;
  assign m_axi_araddr[13] = \<const0> ;
  assign m_axi_araddr[12] = \<const0> ;
  assign m_axi_araddr[11] = \<const0> ;
  assign m_axi_araddr[10] = \<const0> ;
  assign m_axi_araddr[9] = \<const0> ;
  assign m_axi_araddr[8] = \<const0> ;
  assign m_axi_araddr[7] = \<const0> ;
  assign m_axi_araddr[6] = \<const0> ;
  assign m_axi_araddr[5] = \<const0> ;
  assign m_axi_araddr[4] = \<const0> ;
  assign m_axi_araddr[3] = \<const0> ;
  assign m_axi_araddr[2] = \<const0> ;
  assign m_axi_araddr[1] = \<const0> ;
  assign m_axi_araddr[0] = \<const0> ;
  assign m_axi_arburst[1] = \<const0> ;
  assign m_axi_arburst[0] = \<const0> ;
  assign m_axi_arcache[3] = \<const0> ;
  assign m_axi_arcache[2] = \<const0> ;
  assign m_axi_arcache[1] = \<const0> ;
  assign m_axi_arcache[0] = \<const0> ;
  assign m_axi_arlen[7] = \<const0> ;
  assign m_axi_arlen[6] = \<const0> ;
  assign m_axi_arlen[5] = \<const0> ;
  assign m_axi_arlen[4] = \<const0> ;
  assign m_axi_arlen[3] = \<const0> ;
  assign m_axi_arlen[2] = \<const0> ;
  assign m_axi_arlen[1] = \<const0> ;
  assign m_axi_arlen[0] = \<const0> ;
  assign m_axi_arlock[0] = \<const0> ;
  assign m_axi_arprot[2] = \<const0> ;
  assign m_axi_arprot[1] = \<const0> ;
  assign m_axi_arprot[0] = \<const0> ;
  assign m_axi_arqos[3] = \<const0> ;
  assign m_axi_arqos[2] = \<const0> ;
  assign m_axi_arqos[1] = \<const0> ;
  assign m_axi_arqos[0] = \<const0> ;
  assign m_axi_arregion[3] = \<const0> ;
  assign m_axi_arregion[2] = \<const0> ;
  assign m_axi_arregion[1] = \<const0> ;
  assign m_axi_arregion[0] = \<const0> ;
  assign m_axi_arsize[2] = \<const0> ;
  assign m_axi_arsize[1] = \<const0> ;
  assign m_axi_arsize[0] = \<const0> ;
  assign m_axi_arvalid = \<const0> ;
  assign m_axi_awaddr[38] = \<const0> ;
  assign m_axi_awaddr[37] = \<const0> ;
  assign m_axi_awaddr[36] = \<const0> ;
  assign m_axi_awaddr[35] = \<const0> ;
  assign m_axi_awaddr[34] = \<const0> ;
  assign m_axi_awaddr[33] = \<const0> ;
  assign m_axi_awaddr[32] = \<const0> ;
  assign m_axi_awaddr[31] = \<const0> ;
  assign m_axi_awaddr[30] = \<const0> ;
  assign m_axi_awaddr[29] = \<const0> ;
  assign m_axi_awaddr[28] = \<const0> ;
  assign m_axi_awaddr[27] = \<const0> ;
  assign m_axi_awaddr[26] = \<const0> ;
  assign m_axi_awaddr[25] = \<const0> ;
  assign m_axi_awaddr[24] = \<const0> ;
  assign m_axi_awaddr[23] = \<const0> ;
  assign m_axi_awaddr[22] = \<const0> ;
  assign m_axi_awaddr[21] = \<const0> ;
  assign m_axi_awaddr[20] = \<const0> ;
  assign m_axi_awaddr[19] = \<const0> ;
  assign m_axi_awaddr[18] = \<const0> ;
  assign m_axi_awaddr[17] = \<const0> ;
  assign m_axi_awaddr[16] = \<const0> ;
  assign m_axi_awaddr[15] = \<const0> ;
  assign m_axi_awaddr[14] = \<const0> ;
  assign m_axi_awaddr[13] = \<const0> ;
  assign m_axi_awaddr[12] = \<const0> ;
  assign m_axi_awaddr[11] = \<const0> ;
  assign m_axi_awaddr[10] = \<const0> ;
  assign m_axi_awaddr[9] = \<const0> ;
  assign m_axi_awaddr[8] = \<const0> ;
  assign m_axi_awaddr[7] = \<const0> ;
  assign m_axi_awaddr[6] = \<const0> ;
  assign m_axi_awaddr[5] = \<const0> ;
  assign m_axi_awaddr[4] = \<const0> ;
  assign m_axi_awaddr[3] = \<const0> ;
  assign m_axi_awaddr[2] = \<const0> ;
  assign m_axi_awaddr[1] = \<const0> ;
  assign m_axi_awaddr[0] = \<const0> ;
  assign m_axi_awburst[1] = \<const0> ;
  assign m_axi_awburst[0] = \<const0> ;
  assign m_axi_awcache[3] = \<const0> ;
  assign m_axi_awcache[2] = \<const0> ;
  assign m_axi_awcache[1] = \<const0> ;
  assign m_axi_awcache[0] = \<const0> ;
  assign m_axi_awlen[7] = \<const0> ;
  assign m_axi_awlen[6] = \<const0> ;
  assign m_axi_awlen[5] = \<const0> ;
  assign m_axi_awlen[4] = \<const0> ;
  assign m_axi_awlen[3] = \<const0> ;
  assign m_axi_awlen[2] = \<const0> ;
  assign m_axi_awlen[1] = \<const0> ;
  assign m_axi_awlen[0] = \<const0> ;
  assign m_axi_awlock[0] = \<const0> ;
  assign m_axi_awprot[2] = \<const0> ;
  assign m_axi_awprot[1] = \<const0> ;
  assign m_axi_awprot[0] = \<const0> ;
  assign m_axi_awqos[3] = \<const0> ;
  assign m_axi_awqos[2] = \<const0> ;
  assign m_axi_awqos[1] = \<const0> ;
  assign m_axi_awqos[0] = \<const0> ;
  assign m_axi_awregion[3] = \<const0> ;
  assign m_axi_awregion[2] = \<const0> ;
  assign m_axi_awregion[1] = \<const0> ;
  assign m_axi_awregion[0] = \<const0> ;
  assign m_axi_awsize[2] = \<const0> ;
  assign m_axi_awsize[1] = \<const0> ;
  assign m_axi_awsize[0] = \<const0> ;
  assign m_axi_awvalid = \<const0> ;
  assign m_axi_bready = \<const0> ;
  assign m_axi_rready = \<const0> ;
  assign m_axi_wdata[511] = \<const0> ;
  assign m_axi_wdata[510] = \<const0> ;
  assign m_axi_wdata[509] = \<const0> ;
  assign m_axi_wdata[508] = \<const0> ;
  assign m_axi_wdata[507] = \<const0> ;
  assign m_axi_wdata[506] = \<const0> ;
  assign m_axi_wdata[505] = \<const0> ;
  assign m_axi_wdata[504] = \<const0> ;
  assign m_axi_wdata[503] = \<const0> ;
  assign m_axi_wdata[502] = \<const0> ;
  assign m_axi_wdata[501] = \<const0> ;
  assign m_axi_wdata[500] = \<const0> ;
  assign m_axi_wdata[499] = \<const0> ;
  assign m_axi_wdata[498] = \<const0> ;
  assign m_axi_wdata[497] = \<const0> ;
  assign m_axi_wdata[496] = \<const0> ;
  assign m_axi_wdata[495] = \<const0> ;
  assign m_axi_wdata[494] = \<const0> ;
  assign m_axi_wdata[493] = \<const0> ;
  assign m_axi_wdata[492] = \<const0> ;
  assign m_axi_wdata[491] = \<const0> ;
  assign m_axi_wdata[490] = \<const0> ;
  assign m_axi_wdata[489] = \<const0> ;
  assign m_axi_wdata[488] = \<const0> ;
  assign m_axi_wdata[487] = \<const0> ;
  assign m_axi_wdata[486] = \<const0> ;
  assign m_axi_wdata[485] = \<const0> ;
  assign m_axi_wdata[484] = \<const0> ;
  assign m_axi_wdata[483] = \<const0> ;
  assign m_axi_wdata[482] = \<const0> ;
  assign m_axi_wdata[481] = \<const0> ;
  assign m_axi_wdata[480] = \<const0> ;
  assign m_axi_wdata[479] = \<const0> ;
  assign m_axi_wdata[478] = \<const0> ;
  assign m_axi_wdata[477] = \<const0> ;
  assign m_axi_wdata[476] = \<const0> ;
  assign m_axi_wdata[475] = \<const0> ;
  assign m_axi_wdata[474] = \<const0> ;
  assign m_axi_wdata[473] = \<const0> ;
  assign m_axi_wdata[472] = \<const0> ;
  assign m_axi_wdata[471] = \<const0> ;
  assign m_axi_wdata[470] = \<const0> ;
  assign m_axi_wdata[469] = \<const0> ;
  assign m_axi_wdata[468] = \<const0> ;
  assign m_axi_wdata[467] = \<const0> ;
  assign m_axi_wdata[466] = \<const0> ;
  assign m_axi_wdata[465] = \<const0> ;
  assign m_axi_wdata[464] = \<const0> ;
  assign m_axi_wdata[463] = \<const0> ;
  assign m_axi_wdata[462] = \<const0> ;
  assign m_axi_wdata[461] = \<const0> ;
  assign m_axi_wdata[460] = \<const0> ;
  assign m_axi_wdata[459] = \<const0> ;
  assign m_axi_wdata[458] = \<const0> ;
  assign m_axi_wdata[457] = \<const0> ;
  assign m_axi_wdata[456] = \<const0> ;
  assign m_axi_wdata[455] = \<const0> ;
  assign m_axi_wdata[454] = \<const0> ;
  assign m_axi_wdata[453] = \<const0> ;
  assign m_axi_wdata[452] = \<const0> ;
  assign m_axi_wdata[451] = \<const0> ;
  assign m_axi_wdata[450] = \<const0> ;
  assign m_axi_wdata[449] = \<const0> ;
  assign m_axi_wdata[448] = \<const0> ;
  assign m_axi_wdata[447] = \<const0> ;
  assign m_axi_wdata[446] = \<const0> ;
  assign m_axi_wdata[445] = \<const0> ;
  assign m_axi_wdata[444] = \<const0> ;
  assign m_axi_wdata[443] = \<const0> ;
  assign m_axi_wdata[442] = \<const0> ;
  assign m_axi_wdata[441] = \<const0> ;
  assign m_axi_wdata[440] = \<const0> ;
  assign m_axi_wdata[439] = \<const0> ;
  assign m_axi_wdata[438] = \<const0> ;
  assign m_axi_wdata[437] = \<const0> ;
  assign m_axi_wdata[436] = \<const0> ;
  assign m_axi_wdata[435] = \<const0> ;
  assign m_axi_wdata[434] = \<const0> ;
  assign m_axi_wdata[433] = \<const0> ;
  assign m_axi_wdata[432] = \<const0> ;
  assign m_axi_wdata[431] = \<const0> ;
  assign m_axi_wdata[430] = \<const0> ;
  assign m_axi_wdata[429] = \<const0> ;
  assign m_axi_wdata[428] = \<const0> ;
  assign m_axi_wdata[427] = \<const0> ;
  assign m_axi_wdata[426] = \<const0> ;
  assign m_axi_wdata[425] = \<const0> ;
  assign m_axi_wdata[424] = \<const0> ;
  assign m_axi_wdata[423] = \<const0> ;
  assign m_axi_wdata[422] = \<const0> ;
  assign m_axi_wdata[421] = \<const0> ;
  assign m_axi_wdata[420] = \<const0> ;
  assign m_axi_wdata[419] = \<const0> ;
  assign m_axi_wdata[418] = \<const0> ;
  assign m_axi_wdata[417] = \<const0> ;
  assign m_axi_wdata[416] = \<const0> ;
  assign m_axi_wdata[415] = \<const0> ;
  assign m_axi_wdata[414] = \<const0> ;
  assign m_axi_wdata[413] = \<const0> ;
  assign m_axi_wdata[412] = \<const0> ;
  assign m_axi_wdata[411] = \<const0> ;
  assign m_axi_wdata[410] = \<const0> ;
  assign m_axi_wdata[409] = \<const0> ;
  assign m_axi_wdata[408] = \<const0> ;
  assign m_axi_wdata[407] = \<const0> ;
  assign m_axi_wdata[406] = \<const0> ;
  assign m_axi_wdata[405] = \<const0> ;
  assign m_axi_wdata[404] = \<const0> ;
  assign m_axi_wdata[403] = \<const0> ;
  assign m_axi_wdata[402] = \<const0> ;
  assign m_axi_wdata[401] = \<const0> ;
  assign m_axi_wdata[400] = \<const0> ;
  assign m_axi_wdata[399] = \<const0> ;
  assign m_axi_wdata[398] = \<const0> ;
  assign m_axi_wdata[397] = \<const0> ;
  assign m_axi_wdata[396] = \<const0> ;
  assign m_axi_wdata[395] = \<const0> ;
  assign m_axi_wdata[394] = \<const0> ;
  assign m_axi_wdata[393] = \<const0> ;
  assign m_axi_wdata[392] = \<const0> ;
  assign m_axi_wdata[391] = \<const0> ;
  assign m_axi_wdata[390] = \<const0> ;
  assign m_axi_wdata[389] = \<const0> ;
  assign m_axi_wdata[388] = \<const0> ;
  assign m_axi_wdata[387] = \<const0> ;
  assign m_axi_wdata[386] = \<const0> ;
  assign m_axi_wdata[385] = \<const0> ;
  assign m_axi_wdata[384] = \<const0> ;
  assign m_axi_wdata[383] = \<const0> ;
  assign m_axi_wdata[382] = \<const0> ;
  assign m_axi_wdata[381] = \<const0> ;
  assign m_axi_wdata[380] = \<const0> ;
  assign m_axi_wdata[379] = \<const0> ;
  assign m_axi_wdata[378] = \<const0> ;
  assign m_axi_wdata[377] = \<const0> ;
  assign m_axi_wdata[376] = \<const0> ;
  assign m_axi_wdata[375] = \<const0> ;
  assign m_axi_wdata[374] = \<const0> ;
  assign m_axi_wdata[373] = \<const0> ;
  assign m_axi_wdata[372] = \<const0> ;
  assign m_axi_wdata[371] = \<const0> ;
  assign m_axi_wdata[370] = \<const0> ;
  assign m_axi_wdata[369] = \<const0> ;
  assign m_axi_wdata[368] = \<const0> ;
  assign m_axi_wdata[367] = \<const0> ;
  assign m_axi_wdata[366] = \<const0> ;
  assign m_axi_wdata[365] = \<const0> ;
  assign m_axi_wdata[364] = \<const0> ;
  assign m_axi_wdata[363] = \<const0> ;
  assign m_axi_wdata[362] = \<const0> ;
  assign m_axi_wdata[361] = \<const0> ;
  assign m_axi_wdata[360] = \<const0> ;
  assign m_axi_wdata[359] = \<const0> ;
  assign m_axi_wdata[358] = \<const0> ;
  assign m_axi_wdata[357] = \<const0> ;
  assign m_axi_wdata[356] = \<const0> ;
  assign m_axi_wdata[355] = \<const0> ;
  assign m_axi_wdata[354] = \<const0> ;
  assign m_axi_wdata[353] = \<const0> ;
  assign m_axi_wdata[352] = \<const0> ;
  assign m_axi_wdata[351] = \<const0> ;
  assign m_axi_wdata[350] = \<const0> ;
  assign m_axi_wdata[349] = \<const0> ;
  assign m_axi_wdata[348] = \<const0> ;
  assign m_axi_wdata[347] = \<const0> ;
  assign m_axi_wdata[346] = \<const0> ;
  assign m_axi_wdata[345] = \<const0> ;
  assign m_axi_wdata[344] = \<const0> ;
  assign m_axi_wdata[343] = \<const0> ;
  assign m_axi_wdata[342] = \<const0> ;
  assign m_axi_wdata[341] = \<const0> ;
  assign m_axi_wdata[340] = \<const0> ;
  assign m_axi_wdata[339] = \<const0> ;
  assign m_axi_wdata[338] = \<const0> ;
  assign m_axi_wdata[337] = \<const0> ;
  assign m_axi_wdata[336] = \<const0> ;
  assign m_axi_wdata[335] = \<const0> ;
  assign m_axi_wdata[334] = \<const0> ;
  assign m_axi_wdata[333] = \<const0> ;
  assign m_axi_wdata[332] = \<const0> ;
  assign m_axi_wdata[331] = \<const0> ;
  assign m_axi_wdata[330] = \<const0> ;
  assign m_axi_wdata[329] = \<const0> ;
  assign m_axi_wdata[328] = \<const0> ;
  assign m_axi_wdata[327] = \<const0> ;
  assign m_axi_wdata[326] = \<const0> ;
  assign m_axi_wdata[325] = \<const0> ;
  assign m_axi_wdata[324] = \<const0> ;
  assign m_axi_wdata[323] = \<const0> ;
  assign m_axi_wdata[322] = \<const0> ;
  assign m_axi_wdata[321] = \<const0> ;
  assign m_axi_wdata[320] = \<const0> ;
  assign m_axi_wdata[319] = \<const0> ;
  assign m_axi_wdata[318] = \<const0> ;
  assign m_axi_wdata[317] = \<const0> ;
  assign m_axi_wdata[316] = \<const0> ;
  assign m_axi_wdata[315] = \<const0> ;
  assign m_axi_wdata[314] = \<const0> ;
  assign m_axi_wdata[313] = \<const0> ;
  assign m_axi_wdata[312] = \<const0> ;
  assign m_axi_wdata[311] = \<const0> ;
  assign m_axi_wdata[310] = \<const0> ;
  assign m_axi_wdata[309] = \<const0> ;
  assign m_axi_wdata[308] = \<const0> ;
  assign m_axi_wdata[307] = \<const0> ;
  assign m_axi_wdata[306] = \<const0> ;
  assign m_axi_wdata[305] = \<const0> ;
  assign m_axi_wdata[304] = \<const0> ;
  assign m_axi_wdata[303] = \<const0> ;
  assign m_axi_wdata[302] = \<const0> ;
  assign m_axi_wdata[301] = \<const0> ;
  assign m_axi_wdata[300] = \<const0> ;
  assign m_axi_wdata[299] = \<const0> ;
  assign m_axi_wdata[298] = \<const0> ;
  assign m_axi_wdata[297] = \<const0> ;
  assign m_axi_wdata[296] = \<const0> ;
  assign m_axi_wdata[295] = \<const0> ;
  assign m_axi_wdata[294] = \<const0> ;
  assign m_axi_wdata[293] = \<const0> ;
  assign m_axi_wdata[292] = \<const0> ;
  assign m_axi_wdata[291] = \<const0> ;
  assign m_axi_wdata[290] = \<const0> ;
  assign m_axi_wdata[289] = \<const0> ;
  assign m_axi_wdata[288] = \<const0> ;
  assign m_axi_wdata[287] = \<const0> ;
  assign m_axi_wdata[286] = \<const0> ;
  assign m_axi_wdata[285] = \<const0> ;
  assign m_axi_wdata[284] = \<const0> ;
  assign m_axi_wdata[283] = \<const0> ;
  assign m_axi_wdata[282] = \<const0> ;
  assign m_axi_wdata[281] = \<const0> ;
  assign m_axi_wdata[280] = \<const0> ;
  assign m_axi_wdata[279] = \<const0> ;
  assign m_axi_wdata[278] = \<const0> ;
  assign m_axi_wdata[277] = \<const0> ;
  assign m_axi_wdata[276] = \<const0> ;
  assign m_axi_wdata[275] = \<const0> ;
  assign m_axi_wdata[274] = \<const0> ;
  assign m_axi_wdata[273] = \<const0> ;
  assign m_axi_wdata[272] = \<const0> ;
  assign m_axi_wdata[271] = \<const0> ;
  assign m_axi_wdata[270] = \<const0> ;
  assign m_axi_wdata[269] = \<const0> ;
  assign m_axi_wdata[268] = \<const0> ;
  assign m_axi_wdata[267] = \<const0> ;
  assign m_axi_wdata[266] = \<const0> ;
  assign m_axi_wdata[265] = \<const0> ;
  assign m_axi_wdata[264] = \<const0> ;
  assign m_axi_wdata[263] = \<const0> ;
  assign m_axi_wdata[262] = \<const0> ;
  assign m_axi_wdata[261] = \<const0> ;
  assign m_axi_wdata[260] = \<const0> ;
  assign m_axi_wdata[259] = \<const0> ;
  assign m_axi_wdata[258] = \<const0> ;
  assign m_axi_wdata[257] = \<const0> ;
  assign m_axi_wdata[256] = \<const0> ;
  assign m_axi_wdata[255] = \<const0> ;
  assign m_axi_wdata[254] = \<const0> ;
  assign m_axi_wdata[253] = \<const0> ;
  assign m_axi_wdata[252] = \<const0> ;
  assign m_axi_wdata[251] = \<const0> ;
  assign m_axi_wdata[250] = \<const0> ;
  assign m_axi_wdata[249] = \<const0> ;
  assign m_axi_wdata[248] = \<const0> ;
  assign m_axi_wdata[247] = \<const0> ;
  assign m_axi_wdata[246] = \<const0> ;
  assign m_axi_wdata[245] = \<const0> ;
  assign m_axi_wdata[244] = \<const0> ;
  assign m_axi_wdata[243] = \<const0> ;
  assign m_axi_wdata[242] = \<const0> ;
  assign m_axi_wdata[241] = \<const0> ;
  assign m_axi_wdata[240] = \<const0> ;
  assign m_axi_wdata[239] = \<const0> ;
  assign m_axi_wdata[238] = \<const0> ;
  assign m_axi_wdata[237] = \<const0> ;
  assign m_axi_wdata[236] = \<const0> ;
  assign m_axi_wdata[235] = \<const0> ;
  assign m_axi_wdata[234] = \<const0> ;
  assign m_axi_wdata[233] = \<const0> ;
  assign m_axi_wdata[232] = \<const0> ;
  assign m_axi_wdata[231] = \<const0> ;
  assign m_axi_wdata[230] = \<const0> ;
  assign m_axi_wdata[229] = \<const0> ;
  assign m_axi_wdata[228] = \<const0> ;
  assign m_axi_wdata[227] = \<const0> ;
  assign m_axi_wdata[226] = \<const0> ;
  assign m_axi_wdata[225] = \<const0> ;
  assign m_axi_wdata[224] = \<const0> ;
  assign m_axi_wdata[223] = \<const0> ;
  assign m_axi_wdata[222] = \<const0> ;
  assign m_axi_wdata[221] = \<const0> ;
  assign m_axi_wdata[220] = \<const0> ;
  assign m_axi_wdata[219] = \<const0> ;
  assign m_axi_wdata[218] = \<const0> ;
  assign m_axi_wdata[217] = \<const0> ;
  assign m_axi_wdata[216] = \<const0> ;
  assign m_axi_wdata[215] = \<const0> ;
  assign m_axi_wdata[214] = \<const0> ;
  assign m_axi_wdata[213] = \<const0> ;
  assign m_axi_wdata[212] = \<const0> ;
  assign m_axi_wdata[211] = \<const0> ;
  assign m_axi_wdata[210] = \<const0> ;
  assign m_axi_wdata[209] = \<const0> ;
  assign m_axi_wdata[208] = \<const0> ;
  assign m_axi_wdata[207] = \<const0> ;
  assign m_axi_wdata[206] = \<const0> ;
  assign m_axi_wdata[205] = \<const0> ;
  assign m_axi_wdata[204] = \<const0> ;
  assign m_axi_wdata[203] = \<const0> ;
  assign m_axi_wdata[202] = \<const0> ;
  assign m_axi_wdata[201] = \<const0> ;
  assign m_axi_wdata[200] = \<const0> ;
  assign m_axi_wdata[199] = \<const0> ;
  assign m_axi_wdata[198] = \<const0> ;
  assign m_axi_wdata[197] = \<const0> ;
  assign m_axi_wdata[196] = \<const0> ;
  assign m_axi_wdata[195] = \<const0> ;
  assign m_axi_wdata[194] = \<const0> ;
  assign m_axi_wdata[193] = \<const0> ;
  assign m_axi_wdata[192] = \<const0> ;
  assign m_axi_wdata[191] = \<const0> ;
  assign m_axi_wdata[190] = \<const0> ;
  assign m_axi_wdata[189] = \<const0> ;
  assign m_axi_wdata[188] = \<const0> ;
  assign m_axi_wdata[187] = \<const0> ;
  assign m_axi_wdata[186] = \<const0> ;
  assign m_axi_wdata[185] = \<const0> ;
  assign m_axi_wdata[184] = \<const0> ;
  assign m_axi_wdata[183] = \<const0> ;
  assign m_axi_wdata[182] = \<const0> ;
  assign m_axi_wdata[181] = \<const0> ;
  assign m_axi_wdata[180] = \<const0> ;
  assign m_axi_wdata[179] = \<const0> ;
  assign m_axi_wdata[178] = \<const0> ;
  assign m_axi_wdata[177] = \<const0> ;
  assign m_axi_wdata[176] = \<const0> ;
  assign m_axi_wdata[175] = \<const0> ;
  assign m_axi_wdata[174] = \<const0> ;
  assign m_axi_wdata[173] = \<const0> ;
  assign m_axi_wdata[172] = \<const0> ;
  assign m_axi_wdata[171] = \<const0> ;
  assign m_axi_wdata[170] = \<const0> ;
  assign m_axi_wdata[169] = \<const0> ;
  assign m_axi_wdata[168] = \<const0> ;
  assign m_axi_wdata[167] = \<const0> ;
  assign m_axi_wdata[166] = \<const0> ;
  assign m_axi_wdata[165] = \<const0> ;
  assign m_axi_wdata[164] = \<const0> ;
  assign m_axi_wdata[163] = \<const0> ;
  assign m_axi_wdata[162] = \<const0> ;
  assign m_axi_wdata[161] = \<const0> ;
  assign m_axi_wdata[160] = \<const0> ;
  assign m_axi_wdata[159] = \<const0> ;
  assign m_axi_wdata[158] = \<const0> ;
  assign m_axi_wdata[157] = \<const0> ;
  assign m_axi_wdata[156] = \<const0> ;
  assign m_axi_wdata[155] = \<const0> ;
  assign m_axi_wdata[154] = \<const0> ;
  assign m_axi_wdata[153] = \<const0> ;
  assign m_axi_wdata[152] = \<const0> ;
  assign m_axi_wdata[151] = \<const0> ;
  assign m_axi_wdata[150] = \<const0> ;
  assign m_axi_wdata[149] = \<const0> ;
  assign m_axi_wdata[148] = \<const0> ;
  assign m_axi_wdata[147] = \<const0> ;
  assign m_axi_wdata[146] = \<const0> ;
  assign m_axi_wdata[145] = \<const0> ;
  assign m_axi_wdata[144] = \<const0> ;
  assign m_axi_wdata[143] = \<const0> ;
  assign m_axi_wdata[142] = \<const0> ;
  assign m_axi_wdata[141] = \<const0> ;
  assign m_axi_wdata[140] = \<const0> ;
  assign m_axi_wdata[139] = \<const0> ;
  assign m_axi_wdata[138] = \<const0> ;
  assign m_axi_wdata[137] = \<const0> ;
  assign m_axi_wdata[136] = \<const0> ;
  assign m_axi_wdata[135] = \<const0> ;
  assign m_axi_wdata[134] = \<const0> ;
  assign m_axi_wdata[133] = \<const0> ;
  assign m_axi_wdata[132] = \<const0> ;
  assign m_axi_wdata[131] = \<const0> ;
  assign m_axi_wdata[130] = \<const0> ;
  assign m_axi_wdata[129] = \<const0> ;
  assign m_axi_wdata[128] = \<const0> ;
  assign m_axi_wdata[127] = \<const0> ;
  assign m_axi_wdata[126] = \<const0> ;
  assign m_axi_wdata[125] = \<const0> ;
  assign m_axi_wdata[124] = \<const0> ;
  assign m_axi_wdata[123] = \<const0> ;
  assign m_axi_wdata[122] = \<const0> ;
  assign m_axi_wdata[121] = \<const0> ;
  assign m_axi_wdata[120] = \<const0> ;
  assign m_axi_wdata[119] = \<const0> ;
  assign m_axi_wdata[118] = \<const0> ;
  assign m_axi_wdata[117] = \<const0> ;
  assign m_axi_wdata[116] = \<const0> ;
  assign m_axi_wdata[115] = \<const0> ;
  assign m_axi_wdata[114] = \<const0> ;
  assign m_axi_wdata[113] = \<const0> ;
  assign m_axi_wdata[112] = \<const0> ;
  assign m_axi_wdata[111] = \<const0> ;
  assign m_axi_wdata[110] = \<const0> ;
  assign m_axi_wdata[109] = \<const0> ;
  assign m_axi_wdata[108] = \<const0> ;
  assign m_axi_wdata[107] = \<const0> ;
  assign m_axi_wdata[106] = \<const0> ;
  assign m_axi_wdata[105] = \<const0> ;
  assign m_axi_wdata[104] = \<const0> ;
  assign m_axi_wdata[103] = \<const0> ;
  assign m_axi_wdata[102] = \<const0> ;
  assign m_axi_wdata[101] = \<const0> ;
  assign m_axi_wdata[100] = \<const0> ;
  assign m_axi_wdata[99] = \<const0> ;
  assign m_axi_wdata[98] = \<const0> ;
  assign m_axi_wdata[97] = \<const0> ;
  assign m_axi_wdata[96] = \<const0> ;
  assign m_axi_wdata[95] = \<const0> ;
  assign m_axi_wdata[94] = \<const0> ;
  assign m_axi_wdata[93] = \<const0> ;
  assign m_axi_wdata[92] = \<const0> ;
  assign m_axi_wdata[91] = \<const0> ;
  assign m_axi_wdata[90] = \<const0> ;
  assign m_axi_wdata[89] = \<const0> ;
  assign m_axi_wdata[88] = \<const0> ;
  assign m_axi_wdata[87] = \<const0> ;
  assign m_axi_wdata[86] = \<const0> ;
  assign m_axi_wdata[85] = \<const0> ;
  assign m_axi_wdata[84] = \<const0> ;
  assign m_axi_wdata[83] = \<const0> ;
  assign m_axi_wdata[82] = \<const0> ;
  assign m_axi_wdata[81] = \<const0> ;
  assign m_axi_wdata[80] = \<const0> ;
  assign m_axi_wdata[79] = \<const0> ;
  assign m_axi_wdata[78] = \<const0> ;
  assign m_axi_wdata[77] = \<const0> ;
  assign m_axi_wdata[76] = \<const0> ;
  assign m_axi_wdata[75] = \<const0> ;
  assign m_axi_wdata[74] = \<const0> ;
  assign m_axi_wdata[73] = \<const0> ;
  assign m_axi_wdata[72] = \<const0> ;
  assign m_axi_wdata[71] = \<const0> ;
  assign m_axi_wdata[70] = \<const0> ;
  assign m_axi_wdata[69] = \<const0> ;
  assign m_axi_wdata[68] = \<const0> ;
  assign m_axi_wdata[67] = \<const0> ;
  assign m_axi_wdata[66] = \<const0> ;
  assign m_axi_wdata[65] = \<const0> ;
  assign m_axi_wdata[64] = \<const0> ;
  assign m_axi_wdata[63] = \<const0> ;
  assign m_axi_wdata[62] = \<const0> ;
  assign m_axi_wdata[61] = \<const0> ;
  assign m_axi_wdata[60] = \<const0> ;
  assign m_axi_wdata[59] = \<const0> ;
  assign m_axi_wdata[58] = \<const0> ;
  assign m_axi_wdata[57] = \<const0> ;
  assign m_axi_wdata[56] = \<const0> ;
  assign m_axi_wdata[55] = \<const0> ;
  assign m_axi_wdata[54] = \<const0> ;
  assign m_axi_wdata[53] = \<const0> ;
  assign m_axi_wdata[52] = \<const0> ;
  assign m_axi_wdata[51] = \<const0> ;
  assign m_axi_wdata[50] = \<const0> ;
  assign m_axi_wdata[49] = \<const0> ;
  assign m_axi_wdata[48] = \<const0> ;
  assign m_axi_wdata[47] = \<const0> ;
  assign m_axi_wdata[46] = \<const0> ;
  assign m_axi_wdata[45] = \<const0> ;
  assign m_axi_wdata[44] = \<const0> ;
  assign m_axi_wdata[43] = \<const0> ;
  assign m_axi_wdata[42] = \<const0> ;
  assign m_axi_wdata[41] = \<const0> ;
  assign m_axi_wdata[40] = \<const0> ;
  assign m_axi_wdata[39] = \<const0> ;
  assign m_axi_wdata[38] = \<const0> ;
  assign m_axi_wdata[37] = \<const0> ;
  assign m_axi_wdata[36] = \<const0> ;
  assign m_axi_wdata[35] = \<const0> ;
  assign m_axi_wdata[34] = \<const0> ;
  assign m_axi_wdata[33] = \<const0> ;
  assign m_axi_wdata[32] = \<const0> ;
  assign m_axi_wdata[31] = \<const0> ;
  assign m_axi_wdata[30] = \<const0> ;
  assign m_axi_wdata[29] = \<const0> ;
  assign m_axi_wdata[28] = \<const0> ;
  assign m_axi_wdata[27] = \<const0> ;
  assign m_axi_wdata[26] = \<const0> ;
  assign m_axi_wdata[25] = \<const0> ;
  assign m_axi_wdata[24] = \<const0> ;
  assign m_axi_wdata[23] = \<const0> ;
  assign m_axi_wdata[22] = \<const0> ;
  assign m_axi_wdata[21] = \<const0> ;
  assign m_axi_wdata[20] = \<const0> ;
  assign m_axi_wdata[19] = \<const0> ;
  assign m_axi_wdata[18] = \<const0> ;
  assign m_axi_wdata[17] = \<const0> ;
  assign m_axi_wdata[16] = \<const0> ;
  assign m_axi_wdata[15] = \<const0> ;
  assign m_axi_wdata[14] = \<const0> ;
  assign m_axi_wdata[13] = \<const0> ;
  assign m_axi_wdata[12] = \<const0> ;
  assign m_axi_wdata[11] = \<const0> ;
  assign m_axi_wdata[10] = \<const0> ;
  assign m_axi_wdata[9] = \<const0> ;
  assign m_axi_wdata[8] = \<const0> ;
  assign m_axi_wdata[7] = \<const0> ;
  assign m_axi_wdata[6] = \<const0> ;
  assign m_axi_wdata[5] = \<const0> ;
  assign m_axi_wdata[4] = \<const0> ;
  assign m_axi_wdata[3] = \<const0> ;
  assign m_axi_wdata[2] = \<const0> ;
  assign m_axi_wdata[1] = \<const0> ;
  assign m_axi_wdata[0] = \<const0> ;
  assign m_axi_wlast = \<const0> ;
  assign m_axi_wstrb[63] = \<const0> ;
  assign m_axi_wstrb[62] = \<const0> ;
  assign m_axi_wstrb[61] = \<const0> ;
  assign m_axi_wstrb[60] = \<const0> ;
  assign m_axi_wstrb[59] = \<const0> ;
  assign m_axi_wstrb[58] = \<const0> ;
  assign m_axi_wstrb[57] = \<const0> ;
  assign m_axi_wstrb[56] = \<const0> ;
  assign m_axi_wstrb[55] = \<const0> ;
  assign m_axi_wstrb[54] = \<const0> ;
  assign m_axi_wstrb[53] = \<const0> ;
  assign m_axi_wstrb[52] = \<const0> ;
  assign m_axi_wstrb[51] = \<const0> ;
  assign m_axi_wstrb[50] = \<const0> ;
  assign m_axi_wstrb[49] = \<const0> ;
  assign m_axi_wstrb[48] = \<const0> ;
  assign m_axi_wstrb[47] = \<const0> ;
  assign m_axi_wstrb[46] = \<const0> ;
  assign m_axi_wstrb[45] = \<const0> ;
  assign m_axi_wstrb[44] = \<const0> ;
  assign m_axi_wstrb[43] = \<const0> ;
  assign m_axi_wstrb[42] = \<const0> ;
  assign m_axi_wstrb[41] = \<const0> ;
  assign m_axi_wstrb[40] = \<const0> ;
  assign m_axi_wstrb[39] = \<const0> ;
  assign m_axi_wstrb[38] = \<const0> ;
  assign m_axi_wstrb[37] = \<const0> ;
  assign m_axi_wstrb[36] = \<const0> ;
  assign m_axi_wstrb[35] = \<const0> ;
  assign m_axi_wstrb[34] = \<const0> ;
  assign m_axi_wstrb[33] = \<const0> ;
  assign m_axi_wstrb[32] = \<const0> ;
  assign m_axi_wstrb[31] = \<const0> ;
  assign m_axi_wstrb[30] = \<const0> ;
  assign m_axi_wstrb[29] = \<const0> ;
  assign m_axi_wstrb[28] = \<const0> ;
  assign m_axi_wstrb[27] = \<const0> ;
  assign m_axi_wstrb[26] = \<const0> ;
  assign m_axi_wstrb[25] = \<const0> ;
  assign m_axi_wstrb[24] = \<const0> ;
  assign m_axi_wstrb[23] = \<const0> ;
  assign m_axi_wstrb[22] = \<const0> ;
  assign m_axi_wstrb[21] = \<const0> ;
  assign m_axi_wstrb[20] = \<const0> ;
  assign m_axi_wstrb[19] = \<const0> ;
  assign m_axi_wstrb[18] = \<const0> ;
  assign m_axi_wstrb[17] = \<const0> ;
  assign m_axi_wstrb[16] = \<const0> ;
  assign m_axi_wstrb[15] = \<const0> ;
  assign m_axi_wstrb[14] = \<const0> ;
  assign m_axi_wstrb[13] = \<const0> ;
  assign m_axi_wstrb[12] = \<const0> ;
  assign m_axi_wstrb[11] = \<const0> ;
  assign m_axi_wstrb[10] = \<const0> ;
  assign m_axi_wstrb[9] = \<const0> ;
  assign m_axi_wstrb[8] = \<const0> ;
  assign m_axi_wstrb[7] = \<const0> ;
  assign m_axi_wstrb[6] = \<const0> ;
  assign m_axi_wstrb[5] = \<const0> ;
  assign m_axi_wstrb[4] = \<const0> ;
  assign m_axi_wstrb[3] = \<const0> ;
  assign m_axi_wstrb[2] = \<const0> ;
  assign m_axi_wstrb[1] = \<const0> ;
  assign m_axi_wstrb[0] = \<const0> ;
  assign m_axi_wvalid = \<const0> ;
  GND GND
       (.G(\<const0> ));
endmodule
`ifndef GLBL
`define GLBL
`timescale  1 ps / 1 ps

module glbl ();

    parameter ROC_WIDTH = 100000;
    parameter TOC_WIDTH = 0;
    parameter GRES_WIDTH = 10000;
    parameter GRES_START = 10000;

//--------   STARTUP Globals --------------
    wire GSR;
    wire GTS;
    wire GWE;
    wire PRLD;
    wire GRESTORE;
    tri1 p_up_tmp;
    tri (weak1, strong0) PLL_LOCKG = p_up_tmp;

    wire PROGB_GLBL;
    wire CCLKO_GLBL;
    wire FCSBO_GLBL;
    wire [3:0] DO_GLBL;
    wire [3:0] DI_GLBL;
   
    reg GSR_int;
    reg GTS_int;
    reg PRLD_int;
    reg GRESTORE_int;

//--------   JTAG Globals --------------
    wire JTAG_TDO_GLBL;
    wire JTAG_TCK_GLBL;
    wire JTAG_TDI_GLBL;
    wire JTAG_TMS_GLBL;
    wire JTAG_TRST_GLBL;

    reg JTAG_CAPTURE_GLBL;
    reg JTAG_RESET_GLBL;
    reg JTAG_SHIFT_GLBL;
    reg JTAG_UPDATE_GLBL;
    reg JTAG_RUNTEST_GLBL;

    reg JTAG_SEL1_GLBL = 0;
    reg JTAG_SEL2_GLBL = 0 ;
    reg JTAG_SEL3_GLBL = 0;
    reg JTAG_SEL4_GLBL = 0;

    reg JTAG_USER_TDO1_GLBL = 1'bz;
    reg JTAG_USER_TDO2_GLBL = 1'bz;
    reg JTAG_USER_TDO3_GLBL = 1'bz;
    reg JTAG_USER_TDO4_GLBL = 1'bz;

    assign (strong1, weak0) GSR = GSR_int;
    assign (strong1, weak0) GTS = GTS_int;
    assign (weak1, weak0) PRLD = PRLD_int;
    assign (strong1, weak0) GRESTORE = GRESTORE_int;

    initial begin
	GSR_int = 1'b1;
	PRLD_int = 1'b1;
	#(ROC_WIDTH)
	GSR_int = 1'b0;
	PRLD_int = 1'b0;
    end

    initial begin
	GTS_int = 1'b1;
	#(TOC_WIDTH)
	GTS_int = 1'b0;
    end

    initial begin 
	GRESTORE_int = 1'b0;
	#(GRES_START);
	GRESTORE_int = 1'b1;
	#(GRES_WIDTH);
	GRESTORE_int = 1'b0;
    end

endmodule
`endif
